# Generated by Django 4.2.10 on 2024-03-22 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_alter_space_group_alter_space_owner_alter_space_tags'),
        ('api', '0005_alter_chat_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='spaces.folder'),
        ),
    ]
