# Generated by Django 4.2.10 on 2024-03-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tag_remove_chat_tags_chat_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
